version: '3.3'
services:
  website:
    image: aunghtookhine/ecommerce:v1
    container_name: ecommerce_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env