name: Build and Push Docker Image to DockerHub
on: push
jobs:
  push_to_registry:
    name: Push Docker Image to Dockerhub
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      CATEGORY_DIR: ${{ secrets.CATEGORY_DIR }}
      PRODUCT_DIR: ${{ secrets.PRODUCT_DIR }}
      API_JSON_FILENAME: ${{ secrets.API_JSON_FILENAME }}
      API_YAML_FILENAME: ${{ secrets.API_YAML_FILENAME }}
      SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: aunghtookhine/ecommerce:v1
          build-args: |
            MONGO_URI=${MONGO_URI}
            DATABASE_NAME=${DATABASE_NAME}
            CATEGORY_DIR=${CATEGORY_DIR}
            PRODUCT_DIR=${PRODUCT_DIR}
            API_JSON_FILENAME=${API_JSON_FILENAME}
            API_YAML_FILENAME=${API_YAML_FILENAME}
            SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
            JWT_SECRET_KEY=${JWT_SECRET_KEY}